# Generated by Django 3.1.6 on 2021-02-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('PANNED', 'PANNED')], default='PUBLISHED', max_length=50),
        ),
    ]
