# Generated by Django 3.1.6 on 2021-02-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210216_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='published_time',
        ),
    ]
