# Generated by Django 3.1.6 on 2021-02-15 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210216_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_time',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
