# Generated by Django 3.1.6 on 2021-02-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
