# Generated by Django 3.1.6 on 2021-02-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210216_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
