# Generated by Django 3.1.6 on 2021-02-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_auto_20210216_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
