# Generated by Django 3.1.6 on 2021-02-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Hello', max_length=200),
        ),
    ]
