# Generated by Django 3.1.6 on 2021-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20210217_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
