# Generated by Django 3.1.6 on 2021-02-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_post_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
    ]
